# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [5]:
print(np.__version__)
print(np.show_config())

1.22.3
openblas64__info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SU

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [6]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [11]:
x = np.array([1,2,3,4,5,6,7])
  
print("Size of the array: ",x.size)
  
print("Memory size of one array element in bytes: ",x.itemsize)
  

Size of the array:  7
Memory size of one array element in bytes:  4


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [10]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [12]:
x = np.zeros(10)
print(x)
x[4]=1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [13]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [14]:
x=np.arange(1,10)
print(x)
print(x[::-1])

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [15]:
arr=np.random.randint(0,8, size=(3, 3))
print(arr)

[[6 3 3]
 [1 2 0]
 [0 5 0]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [16]:
x=np.array([1,2,0,0,4,0])
np.flatnonzero(x)

array([0, 1, 4], dtype=int64)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [23]:
np.eye(3, k=-0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [26]:
arr=np.random.rand(3,3,3)
print(arr)

[[[0.92377994 0.13411602 0.14732067]
  [0.29404279 0.79192164 0.13415938]
  [0.73026763 0.46082292 0.2304299 ]]

 [[0.14096617 0.41233227 0.63633171]
  [0.97219877 0.92206884 0.65754969]
  [0.26824916 0.71168847 0.53597393]]

 [[0.34547613 0.21539508 0.90119898]
  [0.8725188  0.443098   0.71202552]
  [0.3495127  0.28450982 0.8516554 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [4]:
arr=np.random.rand(10,10)
print(np.amin(arr))
print(np.amax(arr))

0.0006049626695412424
0.9990564339332357


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [6]:
arr=np.random.randn(1, 30)
print(np.mean(arr))

0.12048218418523107


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [7]:
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [14]:
a = [1, 2, 3, 4, 5]
print(np.pad(a, (2, 3), 'constant', constant_values=(0, 0)))
print("\n\n")
x = np.ones((5,5))
print(np.pad(x, (2, 3), 'constant', constant_values=(0, 0)))


[0 0 1 2 3 4 5 0 0 0]



[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [25]:
print(0 * np.nan,"\n",
np.nan == np.nan,"\n",
np.inf > np.nan,"\n",
np.nan - np.nan,"\n",
0.3 == 3 * 0.1)

nan 
 False 
 False 
 nan 
 False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
matrix=np.diag(np.arange(1,5),k=-1)
print(matrix)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [26]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [32]:
# arr=np.random.rand(6,7,8)
# print(arr)
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [33]:
b = np.array([[1, 0], [0, 1]])

np.tile(b, (8, 8))


array([[1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [35]:
x= np.random.random((5,5))
print("Original Array:")
print(x)
max, min = x.max(), x.min()
x = (x - min)/(max - min)
print("After normalization:")
print(x)

Original Array:
[[0.82737968 0.30431418 0.33803257 0.61794748 0.97808058]
 [0.33345003 0.3552716  0.32497385 0.04119527 0.57432319]
 [0.89986763 0.6907077  0.18966957 0.70824106 0.7702228 ]
 [0.12880552 0.02985509 0.80146543 0.11075761 0.63974338]
 [0.56221049 0.21685062 0.4666132  0.4681196  0.54408767]]
After normalization:
[[0.84107061 0.28944496 0.32500443 0.62020311 1.        ]
 [0.32017168 0.34318473 0.31123268 0.01195937 0.57419687]
 [0.91751651 0.69693614 0.16854059 0.71542684 0.78079288]
 [0.10435328 0.         0.8137414  0.08531993 0.64318909]
 [0.5614228  0.19720577 0.46060575 0.46219441 0.54231044]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [36]:
np.dtype([('R', np.uint64), ('G', np.int32), ('B', np.int32), ('A', np.int32)])


dtype([('R', '<u8'), ('G', '<i4'), ('B', '<i4'), ('A', '<i4')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [40]:
x= np.random.random((5,3))
print("X Matrix:")
print(x)
y= np.random.random((3,2))
print("Y matrix:")
print(y)
np.dot(x,y)

X Matrix:
[[6.36839843e-01 4.24579692e-01 7.31566293e-01]
 [6.39493257e-01 3.60565365e-01 3.99703718e-01]
 [3.03340979e-01 6.68626053e-02 4.86942505e-04]
 [5.33639945e-01 1.21565168e-01 6.04932459e-01]
 [6.19717346e-01 1.17917003e-01 8.01788823e-01]]
Y matrix:
[[0.53002786 0.16190923]
 [0.86058445 0.44540164]
 [0.15343475 0.14127774]]


array([[0.81517723, 0.39557277],
       [0.71057463, 0.32060551],
       [0.2183948 , 0.07896321],
       [0.48027879, 0.22601005],
       [0.55296727, 0.2661333 ]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [45]:
arr=np.arange(11)
condition = np.logical_and(arr > 2, arr <= 8)
arr = np.select([~condition, condition], [arr, -arr])
arr

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [47]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [58]:
Z=np.arange(5)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [62]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\91971\AppData\Local\Temp\ipykernel_18140\3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\91971\AppData\Local\Temp\ipykernel_18140\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [71]:
a=np.random.rand(3,3)
print(a)
print("------------------------------")
print(np.copysign(a,-1))
print("------------------------------")
print(np.ceil(a))
print("------------------------------")
print(np.absolute(a))

[[0.37763422 0.98848199 0.70620507]
 [0.46258794 0.64353681 0.25363386]
 [0.67771172 0.15565499 0.45143144]]
------------------------------
[[-0.37763422 -0.98848199 -0.70620507]
 [-0.46258794 -0.64353681 -0.25363386]
 [-0.67771172 -0.15565499 -0.45143144]]
------------------------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
------------------------------
[[0.37763422 0.98848199 0.70620507]
 [0.46258794 0.64353681 0.25363386]
 [0.67771172 0.15565499 0.45143144]]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [76]:
ar1=np.arange(1,49)
ar2=np.arange(11,29)

print("------------------------------")
print(ar1)
print("------------------------------")
print(ar2)
print("------------------------------")
print(np.intersect1d(ar1, ar2))

------------------------------
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
------------------------------
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28]
------------------------------
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [78]:
np.seterr(all='ignore')

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

In [79]:
np.errstate(divide='ignore')

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [80]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [81]:
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow =np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(today)
print(yesterday)
print(tomorrow)

2022-05-29
2022-05-28
2022-05-30


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [84]:
print(np.arange('2016-07', '2016-08',dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [86]:
a=2
b=3
print(np.multiply(np.add(a,b),(np.divide(-a,2))))

-5.0


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [92]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
print("------------------------------")
print(np.floor(a))
print("------------------------------")
print(np.ceil(a))
print("------------------------------")
print(np.trunc(a))

------------------------------
[-2. -2. -1.  0.  1.  1.  2.]
------------------------------
[-1. -1. -0.  1.  2.  2.  2.]
------------------------------
[-1. -1. -0.  0.  1.  1.  2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [96]:
arr=np.random.randint(0,4, size=(5, 5))
print(arr)

[[1 0 3 3 2]
 [3 3 1 0 0]
 [1 1 3 1 2]
 [0 0 0 2 3]
 [1 0 3 0 3]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [99]:
iterable = (x for x in range(11))
np.fromiter(iterable, float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [100]:
np.linspace(0, 1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [104]:
arr=np.random.rand(5,2)
print(arr)
np.sort(arr)

[[0.22230605 0.94839322]
 [0.77982475 0.34231398]
 [0.55705261 0.88699763]
 [0.96773509 0.5072471 ]
 [0.40584384 0.9442817 ]]


array([[0.22230605, 0.94839322],
       [0.34231398, 0.77982475],
       [0.55705261, 0.88699763],
       [0.5072471 , 0.96773509],
       [0.40584384, 0.9442817 ]])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [105]:
X = np.arange(8).reshape((2,2,2))
print(X)
np.add.reduce(X, 0)


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


array([[ 4,  6],
       [ 8, 10]])

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [114]:
x=np.random.rand(5,2)
print(x)
y=np.random.rand(5,2)
print(y)
print("------------------------------")
print(np.allclose(x,y))
print("------------------------------")
print(np.array_equal(x,y))

[[0.63199814 0.2038921 ]
 [0.34434835 0.59410575]
 [0.48919842 0.32834773]
 [0.28140149 0.52620753]
 [0.17565758 0.0624742 ]]
[[0.06764329 0.25661269]
 [0.34165394 0.4924096 ]
 [0.07890444 0.72479888]
 [0.16521449 0.91273541]
 [0.90279688 0.96057899]]
------------------------------
False
------------------------------
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [115]:
x = np.zeros(10)
x.flags.writeable = False
print("Test the array is read-only or not:")
print("Try to change the value of the first element:")
x[0] = 1

Test the array is read-only or not:
Try to change the value of the first element:


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [116]:
x=np.random.rand(10,2)
print(x)

[[0.50562971 0.45735296]
 [0.4798036  0.95674108]
 [0.01874709 0.54852569]
 [0.53755427 0.82884364]
 [0.54445782 0.84146666]
 [0.81478441 0.41945899]
 [0.1175865  0.58766695]
 [0.99014114 0.08411617]
 [0.22093177 0.08259808]
 [0.70498144 0.52562756]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [122]:
x=np.random.rand(10,2)
print(x)
print("\nMax element : ", np.argmax(x))
x[np.argmax(x, axis=0)]=0
print(x)

[[0.84899749 0.40467188]
 [0.72148017 0.87943191]
 [0.30221675 0.60877791]
 [0.87383457 0.87954016]
 [0.3195325  0.60131567]
 [0.48801284 0.60163862]
 [0.91656978 0.71576891]
 [0.14247271 0.31488079]
 [0.65368178 0.22231398]
 [0.42097876 0.22894531]]

Max element :  12
[[0.84899749 0.40467188]
 [0.72148017 0.87943191]
 [0.30221675 0.60877791]
 [0.         0.        ]
 [0.3195325  0.60131567]
 [0.48801284 0.60163862]
 [0.         0.        ]
 [0.14247271 0.31488079]
 [0.65368178 0.22231398]
 [0.42097876 0.22894531]]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [123]:
nx, ny = (3, 2)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)
xv, yv = np.meshgrid(x, y)
xv

array([[0. , 0.5, 1. ],
       [0. , 0.5, 1. ]])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [124]:
np.subtract.outer([1, 2, 3], [4, 5, 6])

array([[-3, -4, -5],
       [-2, -3, -4],
       [-1, -2, -3]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [126]:
ii16 = np.iinfo(np.int16)
print(ii16.min)
print(ii16.max) 



-32768
32767


ValueError: data type <class 'numpy.int16'> not inexact

#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [128]:
np.set_printoptions(precision=4)
np.array([1.123456789])

array([1.1235])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [131]:
x=np.random.rand(10,2,5)
print(x)
print("\nMin closet element : ", np.argmin(x))

[[[0.1155 0.6688 0.6636 0.1905 0.2032]
  [0.8475 0.1467 0.7209 0.4689 0.2411]]

 [[0.6752 0.1725 0.0038 0.0845 0.0636]
  [0.943  0.275  0.198  0.8605 0.0807]]

 [[0.4091 0.7165 0.7766 0.7977 0.8889]
  [0.6698 0.1772 0.0014 0.3224 0.8515]]

 [[0.4672 0.5635 0.4091 0.5679 0.1427]
  [0.5733 0.8069 0.206  0.0637 0.1503]]

 [[0.0475 0.2529 0.304  0.8442 0.6492]
  [0.1262 0.675  0.8466 0.0675 0.0733]]

 [[0.9106 0.8857 0.433  0.0691 0.9824]
  [0.0118 0.2594 0.7455 0.8689 0.2669]]

 [[0.071  0.1441 0.4471 0.8434 0.4733]
  [0.4854 0.6189 0.4001 0.5814 0.8117]]

 [[0.603  0.1551 0.7322 0.9594 0.4877]
  [0.76   0.3224 0.1918 0.4438 0.0898]]

 [[0.3309 0.9475 0.7567 0.0474 0.4763]
  [0.0513 0.6556 0.5144 0.7929 0.5971]]

 [[0.383  0.9179 0.8867 0.0582 0.6192]
  [0.372  0.4866 0.0068 0.4651 0.6062]]]

Min closet element :  27


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [132]:
x =np.random.rand(100,2)
np.atleast_2d(x)

array([[8.9393e-01, 3.1711e-01],
       [3.6550e-01, 6.4999e-01],
       [9.1408e-01, 6.5449e-01],
       [1.7912e-01, 1.4952e-01],
       [1.2549e-01, 1.5902e-01],
       [3.1987e-01, 1.6661e-01],
       [2.6806e-01, 3.6641e-01],
       [8.5012e-01, 3.0077e-01],
       [4.6601e-01, 2.3482e-01],
       [5.4272e-01, 6.5583e-01],
       [4.6096e-01, 8.4444e-01],
       [3.5275e-01, 8.9612e-01],
       [5.6435e-01, 1.9586e-01],
       [6.0372e-01, 5.3924e-01],
       [7.0011e-01, 5.2219e-01],
       [7.6651e-01, 8.9859e-01],
       [9.1269e-01, 9.6116e-01],
       [2.8470e-01, 3.7475e-01],
       [5.2307e-01, 7.1271e-01],
       [7.2461e-01, 4.1107e-01],
       [6.0096e-01, 4.8050e-01],
       [7.1438e-01, 1.5970e-01],
       [7.4379e-01, 7.9178e-01],
       [3.9934e-01, 6.5407e-01],
       [7.8023e-01, 8.1683e-01],
       [5.7953e-01, 6.8990e-01],
       [4.7848e-01, 1.0704e-01],
       [7.3587e-01, 8.7934e-01],
       [9.0490e-01, 6.2614e-02],
       [2.6333e-01, 1.2320e-01],
       [3.

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
aray = np.arange(10, dtype=np.int32)
aray = aray.astype(np.float32, copy=False)
print(aray)

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [3]:
from io import StringIO
string = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
out = np.genfromtxt(string, delimiter=",", dtype=np.int)
print(out)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\91971\AppData\Local\Temp\ipykernel_12776\1258525457.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  out = np.genfromtxt(string, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [136]:
a = np.array([[1, 2], [3, 4]])
for index, x in np.ndenumerate(a):
    print(index, x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [138]:
nx, ny = (3, 2)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)
xv, yv = np.meshgrid(x, y)
print(xv)
print(yv)

[[0.  0.5 1. ]
 [0.  0.5 1. ]]
[[0. 0. 0.]
 [1. 1. 1.]]


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [139]:
a = np.arange(5)
np.put(a, [0, 2], [-44, -55])
print(a)

[-44   1 -55   3   4]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [141]:
x=np.random.rand(10,2)
print(x)
np.mean(x, axis=1)

[[0.4659 0.1525]
 [0.0264 0.1408]
 [0.4075 0.6765]
 [0.1035 0.59  ]
 [0.488  0.7593]
 [0.9454 0.4318]
 [0.1141 0.395 ]
 [0.4805 0.4223]
 [0.0501 0.0967]
 [0.5429 0.0839]]


array([0.3092, 0.0836, 0.542 , 0.3467, 0.6237, 0.6886, 0.2546, 0.4514,
       0.0734, 0.3134])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [142]:
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0], dtype=int64)

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [145]:
x=np.random.rand(10,2)
print(x)
np.any(np.nan)

[[0.9753 0.8655]
 [0.1909 0.4579]
 [0.5653 0.0915]
 [0.8533 0.249 ]
 [0.6181 0.3628]
 [0.2562 0.1651]
 [0.3949 0.1072]
 [0.8277 0.0457]
 [0.8131 0.3084]
 [0.9157 0.2521]]


True

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [149]:
x=np.random.rand(10,2)
abs(x)

array([[0.7568, 0.9565],
       [0.7414, 0.252 ],
       [0.957 , 0.3253],
       [0.0952, 0.5542],
       [0.179 , 0.7565],
       [0.2112, 0.9769],
       [0.2384, 0.8672],
       [0.7272, 0.9185],
       [0.2405, 0.6355],
       [0.239 , 0.1634]])

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [4]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
itr = np.nditer([A,B,None])
for x,y,z in itr: z[...] = x + y
print(itr.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [5]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

aray = NamedArray(np.arange(10), "range_10")
print (aray.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [6]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[6. 1. 2. 2. 5. 2. 3. 2. 4. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [7]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [8]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [9]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))

print(sum)

[[55 61 71 44]
 [51 53 69 60]
 [59 58 46 45]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [12]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.50546628 0.54987175 0.61375768 0.51280879 0.58011257 0.68761742
 0.4615568  0.59666773 0.38816932 0.55436712]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [13]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

array([0.70139227, 1.26759255, 2.02456524, 0.70639889, 1.58768617])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [16]:
x = np.array([1,2,3,4,5])
nx = 3
x_new = np.zeros(len(x) + (len(x)-1)*(nx))
x_new[::nx+1] = x
print(x_new)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [17]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [18]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [19]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 44) ( 0, 85) ( 1, 11) ( 1, 56) ( 1, 69) ( 1, 90) ( 6, 12) ( 6, 44)
 (10, 91) (10, 93) (11, 56) (12, 44) (17, 60) (17, 85) (19, 44) (19, 96)
 (21, 30) (21, 35) (30, 35) (42, 93) (42, 98) (44, 85) (44, 96) (60, 85)
 (69, 90) (89, 96) (89, 97) (91, 93) (93, 98) (96, 97)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [20]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [21]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [22]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [23]:
x = np.random.randint(0,2,100)
np.logical_not(x, out=x)

x = np.random.uniform(-1.0,1.0,100)
np.negative(x, out=x)

array([-0.36603971, -0.30861354, -0.97614395, -0.25113215,  0.83282377,
       -0.77572331, -0.99994824, -0.88460094, -0.3773272 , -0.936369  ,
        0.81404107,  0.67782789,  0.14705918,  0.55020884, -0.16772328,
       -0.40299336,  0.33823384, -0.58178335, -0.58446579, -0.48273984,
        0.97677884,  0.69865159,  0.20300128,  0.4790128 , -0.22742554,
       -0.21796862,  0.29237548,  0.48130224, -0.62219921,  0.54959642,
       -0.06098828,  0.09570449,  0.83515802, -0.82338451, -0.74208377,
       -0.85770865, -0.56040304,  0.585672  ,  0.11760065,  0.07713327,
        0.17881511,  0.2313679 , -0.12110564, -0.72886709,  0.26051768,
        0.03872505, -0.04863601,  0.22357864,  0.65494493, -0.7015995 ,
        0.46586532,  0.16558808,  0.52127419,  0.76709919,  0.39963753,
       -0.42388425, -0.52554501, -0.19591193,  0.40755848, -0.48445736,
        0.24424761,  0.36198869, -0.60290419, -0.96773977, -0.38432867,
        0.17116942,  0.50317018,  0.3366659 ,  0.93274082,  0.99

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [24]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[14.29754017  0.43649279 19.12316173 11.30672442  0.21434913 14.02072605
 14.96023658 12.2061311  14.23138971  3.29044082]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [25]:

P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 9.57788647 11.66293767  0.38546431  2.53644749 13.26117461  3.16193767
   7.07516215  5.61189091  1.68720992  7.45340776]
 [ 2.38864544  7.74291998  8.35223028  3.96085922  2.6482381   4.04895467
   4.93131659  9.72276283  0.05942934  5.03190993]
 [ 0.28396822  5.67638134  3.89761172  0.41831517  3.81401186  4.8107149
   1.62051836  5.63300313  2.73640442  2.47424994]
 [ 5.38467234  5.7762734  11.43198437 16.2489818   2.96471479 12.31897024
   6.30416622 10.26695951 16.13563168 10.31498107]
 [ 9.65670349  9.06674929  2.05130683  5.18879266 12.25757602  1.09523545
   7.71505477  2.75818611  1.11777893  4.707926  ]
 [ 2.29222246  0.06287612  1.27553597  3.76648869  0.42353544 10.20895019
   3.18515664  1.37619303  8.20878717  3.07026927]
 [ 0.66253775  4.40807207  2.37948254  2.00956917  3.57971618  5.70526052
   0.942886    4.00197438  4.180089    1.0844982 ]
 [10.95257732  5.48179933  6.56000077  9.88280261 11.76531919  1.35681928
   9.87282349  2.00933868  5.24716017  0.74749903]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [26]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[4 1 1 2 4 9 7 1 5 3]
 [3 2 7 8 3 4 8 7 6 1]
 [4 9 5 4 7 1 7 4 8 1]
 [6 9 4 8 3 1 8 1 1 6]
 [8 9 1 2 8 4 6 2 1 6]
 [8 4 9 8 4 5 5 5 5 0]
 [7 4 4 7 0 2 2 5 1 1]
 [4 4 6 1 6 9 8 5 3 4]
 [2 6 9 9 4 9 2 7 8 2]
 [3 8 5 7 4 5 3 8 6 7]]
[[0 0 0 0 0]
 [0 4 1 1 2]
 [0 3 2 7 8]
 [0 4 9 5 4]
 [0 6 9 4 8]]


C:\Users\91971\AppData\Local\Temp\ipykernel_12776\1159162857.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [27]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [28]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [29]:
aray = np.random.randint(0,10,50)
print(np.bincount(aray).argmax())

7


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [30]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 0 0]
   [2 4 0]
   [1 2 0]]

  [[0 0 4]
   [4 0 1]
   [2 0 1]]

  [[0 4 2]
   [0 1 1]
   [0 1 4]]

  [[4 2 2]
   [1 1 2]
   [1 4 2]]

  [[2 2 1]
   [1 2 0]
   [4 2 4]]

  [[2 1 1]
   [2 0 3]
   [2 4 3]]

  [[1 1 2]
   [0 3 0]
   [4 3 1]]

  [[1 2 2]
   [3 0 2]
   [3 1 3]]]


 [[[2 4 0]
   [1 2 0]
   [0 3 3]]

  [[4 0 1]
   [2 0 1]
   [3 3 4]]

  [[0 1 1]
   [0 1 4]
   [3 4 2]]

  [[1 1 2]
   [1 4 2]
   [4 2 1]]

  [[1 2 0]
   [4 2 4]
   [2 1 3]]

  [[2 0 3]
   [2 4 3]
   [1 3 1]]

  [[0 3 0]
   [4 3 1]
   [3 1 4]]

  [[3 0 2]
   [3 1 3]
   [1 4 1]]]


 [[[1 2 0]
   [0 3 3]
   [1 3 1]]

  [[2 0 1]
   [3 3 4]
   [3 1 0]]

  [[0 1 4]
   [3 4 2]
   [1 0 2]]

  [[1 4 2]
   [4 2 1]
   [0 2 2]]

  [[4 2 4]
   [2 1 3]
   [2 2 1]]

  [[2 4 3]
   [1 3 1]
   [2 1 0]]

  [[4 3 1]
   [3 1 4]
   [1 0 1]]

  [[3 1 3]
   [1 4 1]
   [0 1 0]]]


 [[[0 3 3]
   [1 3 1]
   [4 4 1]]

  [[3 3 4]
   [3 1 0]
   [4 1 3]]

  [[3 4 2]
   [1 0 2]
   [1 3 3]]

  [[4 2 1]
   [0 2 2]
   [3 3 1]]

  [[2 1 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [31]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 4 13 12 16  9]
 [13  7 12  2 12]
 [12 12  0 42  1]
 [16  2 42  2 10]
 [ 9 12  1 10  4]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [32]:
p, n = 5, 10
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [33]:
x = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(x, np.arange(0, x.shape[0], k), axis=0),
                                       np.arange(0, x.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [34]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [35]:
x = np.arange(10000)
np.random.shuffle(x)
n = 5

print (x[np.argpartition(-x,n)[:n]])

[9998 9997 9999 9995 9996]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [36]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [37]:
x = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(x.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [38]:
x = np.random.rand(5)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

4.15 µs ± 33.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
2.19 µs ± 101 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
5.69 µs ± 43.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [39]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 2 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [40]:
x = np.random.randint(0,5,(10,3))
print(x)
E = np.all(x[:,1:] == x[:,:-1], axis=1)
U = x[~E]
print(U)

[[4 1 0]
 [2 2 0]
 [2 4 1]
 [2 1 3]
 [3 3 1]
 [1 1 4]
 [0 2 3]
 [4 1 1]
 [2 0 2]
 [2 1 4]]
[[4 1 0]
 [2 2 0]
 [2 4 1]
 [2 1 3]
 [3 3 1]
 [1 1 4]
 [0 2 3]
 [4 1 1]
 [2 0 2]
 [2 1 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [41]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [42]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 1 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [43]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B) 

array([[0.15216993, 0.480322  , 0.59373945, 0.44881349, 0.18780432,
        0.61796809, 0.6169992 , 0.44948983, 0.3726125 , 0.12364205],
       [0.04059882, 0.12814956, 0.15840925, 0.11974311, 0.05010605,
        0.16487343, 0.16461493, 0.11992356, 0.09941274, 0.03298761],
       [0.09952422, 0.31414665, 0.38832546, 0.29353904, 0.1228303 ,
        0.4041718 , 0.40353811, 0.29398138, 0.24370104, 0.08086604],
       [0.04630961, 0.14617557, 0.1806917 , 0.13658664, 0.05715416,
        0.18806516, 0.1877703 , 0.13679247, 0.11339652, 0.03762777],
       [0.02598364, 0.08201697, 0.10138347, 0.07663676, 0.03206836,
        0.10552061, 0.10535516, 0.07675225, 0.06362512, 0.02111239],
       [0.0312708 , 0.09870579, 0.12201299, 0.09223082, 0.03859364,
        0.12699195, 0.12679284, 0.0923698 , 0.07657157, 0.02540834],
       [0.12525744, 0.39537314, 0.48873179, 0.36943717, 0.15458959,
        0.5086754 , 0.50787786, 0.3699939 , 0.30671294, 0.10177495],
       [0.01270473, 0.04010227, 0.0495715

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [47]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [48]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [49]:
X = np.random.randn(100) 
N = 1000
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.11534104  0.27796727]
